services:
  together-frontend:
    build:
      context: .
    container_name: together-frontend
    restart: unless-stopped
    ports:
      - "3000:80" #Host:Container
    environment:
      - NODE_ENV=production
      - EXPO_PUBLIC_API_URL=${API_URL}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s