services:
  together-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: together-frontend
    restart: unless-stopped
    ports:
      - "3000:80" #Host:Container
    environment:
      - NODE_ENV=production
      - EXPO_PUBLIC_API_URL=${API_URL}