version: '3.8'

services:
  together-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: together-frontend
    restart: unless-stopped
    ports:
      - "3000:80" #3000 port on server mapped to 80 internal port in container NGINX
    environment:
      - NODE_ENV=production
      - EXPO_PUBLIC_API_URL=${API_URL}
    networks:
      - coolify
      - npm-network #Connect to NPM Proxy network

networks:
  coolify:
    external: true
  npm-network:
    external: true